194 inspection data processing
HSLdevcom/bultti pull request #225
Opened 2021-03-08 07:24 UTC by danieldunderfelt

Closes: #194 

Implement better data handling processes for inspection data, primarily departures, to facilitate a better Inspection and Report user experience. This is done in multiple ways:

- Move the data processing step to right after DRAFT for both inspection types. This was previously before PRODUCTION. For post-inspections, it is now performed in conjunction with the sanction collection step.
- Refactor planned Departure creation to also be performed on a Worker, in line with how ObservedDepartures are created. This removes a heavy process from the main server.
- Improve Departures queue tasks to await previous tasks and not run multiple tasks for the same thing.
- Preload inspection reports into cache when moving through states and when opening the Reports view.

2021-03-09 12:36 UTC, Divinare requested changes
Left some review comments. Found nothing "big"

Testing: I was able to create post inspection, do sanctions and publish it

Btw, I noticed that I was able to create 2 overlapping postInspections, shouldnt there be overlap prevention?:
![2 overlapping postInspections](https://user-images.githubusercontent.com/1419296/110471428-cae77f80-80e4-11eb-9e84-a3c76b82b280.png)

2021-03-09 12:36 UTC, Divinare commented on src/cache.ts
> +  let remover = promisify(client.srem).bind(client)
Shouldn't cache key param be enough if you just say client.del(key)? Or is there a reason to use client.srem and not client.del?

2021-03-09 12:36 UTC, Divinare commented on src/inspection/inspectionStates.ts
> +export async function setInspectionProcessing(inspection: Inspection) {
All of the status change methods methods could have return types `StatusUpdateProps`

2021-03-09 13:53 UTC, danieldunderfelt commented on src/cache.ts
> +export async function cacheSetHas(setKey: string, value: string) {
We're working with Sets, so if you want to make the name longer it would be something like `doesCacheSetIncludeValue`. But I think cacheSetHas is fine enough. The confusing part is "set", which in this context means the Redis Set construct and not "to set something". No amount of letters in the function name will fix that, developers just need to be familiar with the concepts.

2021-03-09 13:54 UTC, danieldunderfelt commented on src/cache.ts
> +export async function cacheSetRemove(setKey: string, value: string) {
Again, this is distinct from just removing a value by a key on the cache. We already have a function for that.

2021-03-09 13:55 UTC, danieldunderfelt commented on src/cache.ts
> +export async function cacheSetAdd(setKey: string, value: string, ttl?: number) {
See previous comments.

2021-03-09 13:56 UTC, danieldunderfelt commented on src/queue/queueUtils.ts
> +export async function awaitJobCompletion(jobId) {
I was used in a previous iteration of the code, but I still see it as a useful tool in the belt.

2021-03-09 13:59 UTC, danieldunderfelt commented on src/inspection/inspectionStates.ts
> +  nextStatus,
No, it's the "next status" that the inspection should be set to. I don't see what would be wrong here.

2021-03-09 13:59 UTC, danieldunderfelt commented on src/cache.ts
> +  let remover = promisify(client.srem).bind(client)
We are working with Redis Sets here, please see the Redis docs about this.

2021-03-09 14:02 UTC, danieldunderfelt commented on src/inspection/inspectionStates.ts
> +export async function setInspectionProcessing(inspection: Inspection) {
It would be `InspectionStatusUpdate`, and type inference is your friend.

2021-03-10 10:55 UTC, Divinare commented on src/cache.ts
> +export async function cacheSetHas(setKey: string, value: string) {
doesCacheSetExist() would also be an option but w/e, this is fine as well

2021-03-10 10:56 UTC, Divinare commented
LGTM

2021-03-10 11:31 UTC, Divinare commented on src/queue.ts
> +  params: any,
Hmm, could this and also `runCachedWorkerTask`'s params be given a type? Now you pretty much have to check how this method has been called before to see what kind of params it takes

2021-03-10 11:35 UTC, Divinare commented on src/queue.ts
> +  params: any,
Now after changing reloadReport -> shouldReloadReport

I call runWorkerTask with "reloadReport: shouldReloadReport" because I wasnt sure if it wants "reloadReport" exactly...

2021-03-10 11:36 UTC, Divinare commented
Also is this an issue? "Btw, I noticed that I was able to create 2 overlapping postInspections with the same "Tuotantojakso", shouldnt there be overlap prevention"

2021-03-11 03:43 UTC, danieldunderfelt commented on src/queue.ts
> +  params: any,
> Hmm, could this and also `runCachedWorkerTask`'s params be given a type? Now you pretty much have to check how this method has been called before to see what kind of params it takes

The params are given directly to the task so typing is a bit hard. So you have to know what params the _task_ wants, not this function. But i've given this a simple type in https://github.com/HSLdevcom/bultti/pull/228, the important part is that it is an object with scalar values.

2021-03-11 03:44 UTC, danieldunderfelt commented on src/queue.ts
> +  params: any,
> Now after changing reloadReport -> shouldReloadReport
> 
> I call runWorkerTask with "reloadReport: shouldReloadReport" because I wasnt sure if it wants "reloadReport" exactly...

I don't understand. Call it with the argument it takes...?

2021-03-11 03:45 UTC, danieldunderfelt commented
> Also is this an issue? "Btw, I noticed that I was able to create 2 overlapping postInspections with the same "Tuotantojakso", shouldnt there be overlap prevention"

Yes, it is an issue. The previous date should be adjusted to end before the new inspection. I'll look into it.

2021-03-11 13:33 UTC, danieldunderfelt commented
I found no issues with the inspection dates.

2021-03-11 15:23 UTC, Divinare commented
I guess we can merge after conflicts are fixed

2021-03-12 03:46 UTC, merged