WIP 203 refactor hfp loading
HSLdevcom/bultti pull request #228
Opened 2021-03-10 10:31 UTC by danieldunderfelt

Closes #203

Improves the user experience regarding loading HFP data, by doing it as a scheduled task for each completed inspection date range. Also improves the performance and memory consumption of the HFP task.

- Use threads for the HFP loading task, one thread per day in the range. Improve memory consumption.
- Create scheduled workers
- Create a scheduled HFP loading task

2021-03-25 08:09 UTC, Divinare requested changes
Nit: i'd like to use "scheduler" instead of "schedule"

A future task could be to validate somehow that all of the HFP data was loaded correctly, new card for this?
  * One option would be; for each inserted data (2500 rows for stopEvents currenly), calc "dateSectionHash (md5sum)"
    * sort all dateSectionHashes and make a dateHash
    * sort all dateHashes belonging to an InspectionDate range, make inspectionDateHash
--> you can then HFP data again and if we get the same inspectionDateHash, we should have all of the HFP data in InspectionDate range

Testing:
1) When I removed a date range, it didn't remove the data from stop_event. Is this ok?
  * Should we have a  that would tell if 

2) When a date range was loading, date progress didn't show in logs output - I think this should be fixed if we use date progress - "what is the point if it doesnt do anything"

3) Stalled jobs bug?
I set a date range for 4.1.2021 - 5.1.2021, data loaded and in the end, was green in UI
After that, it started spamming "Found stalled jobs: 2", in redis tool I was shown:
0	LoadHfpForDateRange:hfpDateRangeLoadingTask:2021-01-04:2021-01-05
1	LoadHfpForDateRange:hfpDateRangeLoadingTask:2021-01-04:2021-01-04
"Clear cache helped" - but shouldn't job keys from cache be cleared after everything has been loaded? Or there should this automation that check if there a new jobs also somehow clean stalled jobs? "Check if data for stalled job is fetched, if yes -> clear, if no -> make a new job" or something

I was able to reproduce this, deleted 4.1.2021 - 5.1.2021 and then added the same range again. After DL, it logs:
Date 2021-01-05 completed [364.404651 s]
All dates data loaded [731.610798 s]
HFP loading task completed [731.635837 s]
Found stalled jobs: 1

LoadHfpForDateRange:hfpDateRangeLoadingTask:2021-01-04:2021-01-05

2021-03-25 09:59 UTC, danieldunderfelt commented on src/AppResolver.ts
> +      await clearAll()
Yes, that would maybe be useful.

2021-03-25 10:01 UTC, danieldunderfelt commented on src/queue/QUEUE.md
> +`jobIdentifier` is a string that identified the job in the queue. If a job matching the ID is already queued, the new job will not be queued.
It could ALSO be there, but I don't want to split these technical docs for individual concepts up into multiple files. I want ONE place where I can read about everything.

2021-03-25 10:01 UTC, danieldunderfelt commented on src/queue/queueManager.ts
> +  jobIdentifier = 'unnamed job',
Yes, true. I'll make the prop non-optional actually!

2021-03-25 10:02 UTC, danieldunderfelt commented on src/inspection/InspectionEntity.ts
> +  inspectionDate?: Lazy<InspectionDate>
But it is not. It is also for Equipment Defect sanctions in the future. I'll add a comment that reflects this!

2021-03-25 10:03 UTC, danieldunderfelt commented on src/worker/queueWorker.ts
>      if (stalledCount > 0) {
That's exactly what this does. It checks for stalled jobs and re-queues any it finds.

2021-03-25 10:11 UTC, danieldunderfelt commented
Review fixes done!

2021-03-25 11:40 UTC, danieldunderfelt commented
> Nit: i'd like to use "scheduler" instead of "schedule"

I think ScheduleWorker woks pretty well.

> A future task could be to validate somehow that all of the HFP data was loaded correctly, new card for this?
> One option would be; for each inserted data (2500 rows for stopEvents currenly), calc "dateSectionHash (md5sum)"
> sort all dateSectionHashes and make a dateHash
> sort all dateHashes belonging to an InspectionDate range, make inspectionDateHash
> --> you can then HFP data again and if we get the same inspectionDateHash, we should have all of the HFP data in
> InspectionDate range

Yes, we should think about this.

> When I removed a date range, it didn't remove the data from stop_event. Is this ok?

This is OK, nothing is created to remove it. And it should not be removed.

For the stalled jobs, that's a feature of the bee-queue package. A job is stalled if the worker process doesn't check in to the queue regularly, which can happen if the event loop gets stuck. An example would be a worker process that hasn't exited completely. Our code should not block the event loop for too long, otherwise the job is seen as stalled and is re-queued.

We can continue fixing on this, but it should work in production where the whole Docker container will crash and be re-created in these cases.

2021-03-26 07:43 UTC, Divinare commented
Yeah I think that we need to look if stalled job issue exists when we deploy this. Doesn't matter for me if it only happens locally

2021-03-26 07:45 UTC, Divinare approved these changes
Review ok, this can be merged!

2021-03-26 08:25 UTC, danieldunderfelt commented
I think HFP progress nice to have and we should make it work at some point. I also think users may want it in the future. So I'd keep it for now.

2021-03-26 08:25 UTC, merged