235 contract validation fixes
HSLdevcom/bultti pull request #237
Opened 2021-03-22 14:14 UTC by Divinare

Closes https://github.com/HSLdevcom/bultti/issues/235

2021-03-24 06:13 UTC, danieldunderfelt requested changes
A good start, but not quite ready yet!

2021-03-24 06:13 UTC, danieldunderfelt commented on src/inspection/InspectionResolver.ts
> +      inspection.procurementUnitContractMap = unitContractMap
This is not only for pre-inspections. Use the `getProcurementUnitsByInspection` function to get the units for any inspection and take the contracts from there.

2021-03-26 10:06 UTC, Divinare commented on src/inspection/inspectionUtils.ts
> +  let isMatchingConditionA = (contract: Contract): boolean => {
This is what I was thinking but here the variable names would get too long:
isContractStartDateWithinInspectionStartDateAndContractEndDateGreaterThanEqualInspectionEnDate
isInspectionFullyCoveredWithContract

More readable is just 2 condition variables. If you want to know exactly what the condition is, read comments or the code.

2021-03-26 10:08 UTC, Divinare commented on src/inspection/inspectionUtils.ts
> +  let isMatchingConditionA = (contract: Contract): boolean => {
Well, one option would be to split that first into two conditions

isContractStartDateWithinInspectionDates
isContractEndDateGreaterOrEqualThanInspectionEndDate
and use them combined with && but i dont think it adds any value to readability

2021-03-26 10:13 UTC, Divinare commented on src/contract/ContractManager.ts
> +    // TODO: remove the code below when all of the existing preInspections have a procurementUnitContractMap
Hmm.... I think better would be to have procurementUnitsMap never empty. When an inspection is created as a draft, we initialize  procurementUnitsMap. When an inspection is made draft -> review, we update procurementUnitsMap

2021-03-26 10:28 UTC, Divinare commented on src/contract/ContractResolver.ts
> +const guardContractBeingUsedInPreInspection = async (
Okay, I think this is a code convention so I updated it here:
https://github.com/HSLdevcom/bultti-ui/pull/64/commits/8532bf85ca9164a90e232394cfabbb5eec42b1de

2021-03-26 12:11 UTC, danieldunderfelt commented on src/contract/ContractManager.ts
> +    // TODO: remove the code below when all of the existing preInspections have a procurementUnitContractMap
Let's do it that way, yes.

2021-03-29 10:21 UTC, Divinare commented
The spec for implenting things related to this is the air, it seems not smart trying to iterate all of this when we aren't even sure of how things should go. This is why we should stop here (leave it in a stable state though!)

--> Left for future tasks:
1) block changing of dates with any non-draft inspections
  - maybe make startDate as uneditable
  - get minimum endDate for contract
2) tests to "get contract date candidates"

What was done here?
0) Review fixes done
1) Contract's cant overlap by clicking "Sopimuksessa mukana"
 - HOWEVER, if you edit contract dates, this can cause contracts to overlap. I think we need lock specbefore going any further with this.
2) You have a temprorary button to init inspection.procurementUnitContractMap

2021-03-30 08:20 UTC, danieldunderfelt commented on src/inspection/inspectionUtils.ts
> +  let isMatchingConditionA = (contract: Contract): boolean => {
Well... the name doesn't need to include everything. But let's go with the current state for now.

2021-03-30 08:20 UTC, merged