205 linked inspection
HSLdevcom/bultti pull request #238
Opened 2021-03-25 07:46 UTC by danieldunderfelt

Closes https://github.com/HSLdevcom/bultti/issues/205

UI PR: https://github.com/HSLdevcom/bultti-ui/pull/65

This PR implements a new way of linking inspections, using a map. Each linked inspection is attached to the host inspection by a date which represents the start of the week. This is saved on the host as a JSON field. When fetching the inspection, the JSON field can be transformed to an InspectionMapping which contains the linked inspection.

The places where inspection links are created have been reduced. When updating linked pre-inspections, the observed requirements are re-created. Post-inspections are validated to ensure it has linked pre-inspections.

- Refactor linked inspections to use InspectionMapping instead of relation.
- Update references and usages of linked pre-inspections.
- Create observed requirements per week based on linked pre-inspections
- Allow the UI to query for updates to linked inspections.

2021-03-31 12:16 UTC, Divinare requested changes
Review done!

2021-03-31 13:59 UTC, Divinare commented
About the decision of hard linking / saving linked inspections to a postInspections; why do we need to save the linked preInspections into inspection? To store just manually edited columns in "Suoritevaatimukset" table you don't have to link preInspections.

Is it because we don't want postInspection to be changed if preInspection related to it changes and postInspection goes from draft -> in_review? We want to relate to the old preInspection until user clicks manually "use the latest preInspections data"

2021-04-01 11:25 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +  inspection: Inspection
Well, they are two separate things: InspectionMapping is the GraphQL type and InspectionIdMap is the internal mapping of startDates to Inspections or inspectionIds. GraphQL doesn't support sending an object with arbitrary keys (the dates), I would have to define every singe one. `InspectionMappings` are sent as an array over GraphQL, InspectionIdMapping is stored as JSON in the database.

I also want `InspectionMapping.inspection` to contain an Inspection object, not just an ID. This is good for the GraphQL API. But InspectionIdMapping primarily contains inspectionIds (but it is possible to also assign Inspection objects, otherwise we'd need a third type...) which can be stored lightly as JSON.

This has nothing to do with editing the percentage quota of the Post-Inspection execution requirement.

2021-04-01 11:27 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +export type InspectionIdMapping = { [startOfWeek: string]: string | Inspection }
Post-inspections are also linked to Equipment Defect inspections, so this is not only for Pre-inspections. And what's wrong with "mapping"?

`weekInspectionMap` could work though 🤔

2021-04-01 11:28 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +export type InspectionMappings = InspectionMapping[]
See previous comment, they are different things and GraphQL sets its own restrictions.

2021-04-01 11:33 UTC, danieldunderfelt commented on src/inspection/InspectionEntity.ts
> +  linkedInspectionsPerWeek?: InspectionIdMapping
They are in different contexts. `linkedInspectionsPerWeek` makes sense on the host inspection, it wouldn't make sense for `InspectionIdMapping` on its own.

Now that I think about it, the GraphQL field for this (currently `inspectionMappings`, just below this) should probably be renamed to `linkedInspections`.

2021-04-01 11:38 UTC, danieldunderfelt commented on src/inspection/InspectionEntity.ts
> +  linkedInspectionUpdateAvailable: boolean
Then we'd need separate query hooks and everything in the UI... I think it's much simpler that these are on the Inspection. They actually do use FieldResolvers, but these fields on the model are required by Type-GraphQL to provide the type. I tried without them first. Note that they are only GraphQL fields, they are not saved in the DB.

2021-04-01 11:42 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +export async function getInspectionPeriodMapping(
`getLinkedInspectionsMap` is fine, but I also think `getInspectionPeriodMapping` is fine. I see no reason to change perfectly fine names just because. It returns a mapping of inspections to periods, and the name reflects this.

2021-04-01 11:47 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +  let inspectionInEffect = orderBy(inspectionsForPeriod, 'version', 'desc')[0]
This is one of the big changes in this PR, that even replaced inspections can be linked. If an inspection is not completely replaced, it is still in effect for the dates that it is in effect for. But `getProductionInspections` just returns the _current_ production inspections with the highest version.

```
Post-Inspection date  |----------------------|
Pre-Inspection v1        |-------|
Pre-Inspection v2                    |-------|
Pre-Inspection v3                                 |-------|
```

In this example `getProductionInspections` would only return the third pre-inspection, but we actually want all other ones too along the way to cover each part of the inspection dates of the post-inspection.

2021-04-01 11:52 UTC, danieldunderfelt commented on src/executionRequirement/observedExecutionRequirement/observedRequirementUtils.ts
> +  let preInspections = await getInspectionMappings(postInspection)
Yes, good point here. `preInspectionMaps` is good, I don't want to make it sound like it is the map which is linked. The pre-inspections are linked THROUGH the map, the map is just glue.

2021-04-01 11:54 UTC, danieldunderfelt commented on src/inspection/InspectionResolver.ts
> +      return []
This is a FieldResolver, so an error here would not be appropriate as pre-inspections are not supposed to have other linked inspections. This will be called for each Inspection which is sent over GraphQL.

2021-04-01 11:56 UTC, danieldunderfelt commented
> To store just manually edited columns in "Suoritevaatimukset" table you don't have to link preInspections.

Again, this does not have anything to do with that.

This is because the linked inspections are related, and the link should not be loose as that would result in potentially changing data.

2021-04-06 05:41 UTC, danieldunderfelt commented
Updated naming of various things related to linked inspections.

2021-04-06 07:01 UTC, Divinare commented on src/inspection/InspectionEntity.ts
> +  linkedInspectionUpdateAvailable: boolean
I see, you actually have less code when using in a model

I think we could put these graphql only fields to the bottom of entity classes column list, leave some comment above them:
// Graphql only fields

to improve readability

2021-04-06 07:05 UTC, Divinare commented on src/inspection/InspectionResolver.ts
> +      return []
I see, my mistake - didn't look into @FieldResolver! I'm still quite new in typegraphql

2021-04-06 08:38 UTC, Divinare reviewed
Reviewed changes, that new naming is more descriptive!

Yeah some misunderstandings on my part, left some answers to the review comments.

I see why that hard linking exists, commented reasoning about it

2021-04-06 08:38 UTC, Divinare commented on src/inspection/inspectionLinks.ts
> +  let inspectionInEffect = orderBy(inspectionsForPeriod, 'version', 'desc')[0]
Ah I see, you can have partly replaced inspections still in effect for some weeks
```
Post-Inspection date |-----------------------|
Pre-Inspection v1      |-----------------------|
Pre-Inspection v2                |---------------|
```
Here v1 is still valid for some of the time, v2 is valid for like 66% of the time

Also maybe my idea was to combine two functions into one but maybe it's better like having two functions

2021-04-06 08:38 UTC, Divinare commented on src/inspection/inspectionLinks.ts
> +    if (!productionInspection) {
Hmm, this is something that should never happen right? And if it happens, then we have some issue somewhere. I think we could safely throw an error here to indicate that something is wrong

2021-04-06 09:34 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +  let inspectionInEffect = orderBy(inspectionsForPeriod, 'version', 'desc')[0]
Yes!

2021-04-06 09:38 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +    if (!productionInspection) {
This will happen if the user attempts to create a post-inspection for a period where there are no pre-inspections in effect. In this case the inspection validation already notifies the user about this and they can either change the inspection period or try again when there are pre-inspections available. I don't think an additional error here is necessary, as we already have validation and user guidance for this case.

2021-04-06 09:41 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +    return {}
The issue is that both functions independently check for the same thing and return false. So if we only return from the function for one case Typescript still thinks the other one can be undefined or falsy.

The thing they check is that the inspection type can have linked inspections, so sure, we can have some logging here, but I don't think it's very important.

2021-04-06 09:47 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +  inspection: Inspection
We need linked inspections in order to fetch their planned execution requirements. What the post-inspection does with the execution requirements after that is none of the pre-inspection's business. If the linked inspection updates however, the execution requirements need to be refetched from the new pre-inspections and the new ones will replace the current execution requirements for the post-inspection, edited or not. That's why there is a warning in the UI.

Currently only the planned percentage value (eg. "Osuus %") is picked from the pre-inspection requirements, but this is an inconsequential detail. Conceptually the whole execution requirement is fetched and will replace any current requirements on the post-inspection, so we should talk about this in those terms.

2021-04-06 09:49 UTC, danieldunderfelt commented on src/inspection/InspectionResolver.ts
> +      return []
That's OK! Good to learn.

2021-04-06 09:52 UTC, danieldunderfelt commented on src/inspection/InspectionEntity.ts
> +  static async getCurrentProduction({
Hmm, maybe this is not the appropriate place to document the stack identifier. Instead I'd document it on the function that creates it (although the function is very simple and it is not difficult to figure out what it does).

I'll update the name of this to `getCurrentInProductionInspection`.

2021-04-06 09:57 UTC, danieldunderfelt commented on src/inspection/InspectionEntity.ts
> +  linkedInspectionUpdateAvailable: boolean
Hmm not so sure about that. I find it's more useful to have them close to other related props (eg. `weekInspectionMap` in this case). But sure, if they are standalone they can go to the bottom.

Also, the decorators document more than enough if the prop is for GraphQL, database or both. A comment can be added above (as I have done here) if more explanation is needed. I think it's necessary for any developer on Bultti to know what @Field and @Column do and mean.

2021-04-06 10:15 UTC, Divinare approved these changes
Approving! I would only suggest this:

_Hmm, this is something that should never happen right? And if it happens, then we have some issue somewhere. I think we could safely throw an error here to indicate that something is wrong_

2021-04-06 10:17 UTC, Divinare commented on src/inspection/inspectionLinks.ts
> +    if (!productionInspection) {
Yeah this is why this shouldn't never happen. But if a developer makes a mistake, this can happen (this is why I would throw an error). It's something I call as sanity check

2021-04-06 10:20 UTC, Divinare commented on src/inspection/inspectionLinks.ts
> +    if (!productionInspection) {
My point was that it doesn't hurt throwing error there. Also the error msg indicates to the reader that it shouldn't never happen

2021-04-06 11:56 UTC, danieldunderfelt commented
> Hmm, this is something that should never happen right? And if it happens, then we have some issue somewhere. I think we could safely throw an error here to indicate that something is wrong

I tried replying to that but Github doesn't show my reply... I said that it's not needed, the inspection is already validated to have linked inspections if it should have them. No use for an additional error that would just throw a stick in the wheels.

2021-04-06 11:58 UTC, merged