220 sanction updates
HSLdevcom/bultti pull request #246
Opened 2021-04-06 12:42 UTC by danieldunderfelt

Issue: https://github.com/HSLdevcom/bultti/issues/220

UI PR:

- Add values that triggered the sanction to the sanction row.
- Various fixes and updates along the way

2021-04-08 09:24 UTC, Divinare requested changes
Review done! Didn't find any bugs, just added some code improvement proposals

2021-04-08 09:24 UTC, Divinare commented on src/departure/observedDeparture/createObservedDeparturesTask.ts
> +                dayTypeDef.effectiveDayType !== dayTypeDef.normalDayType
I'd also rename the variables like this:
```
export interface DayTypeDefinition {
  date: Date
  sourceDayType: string // Ma-Su + e.g. Ju
  targetDayType: string // Ma-Su
  targetDayExceptionType: DayExceptionType
}
```

2021-04-09 04:37 UTC, danieldunderfelt commented on src/departure/observedDepartureAnalysis/equipmentTypeDepartureAnalysis.ts
> +      }`,
it's from JORE. If it is required the sanction may be higher than if not required. Both are sanctioned though. The Contract needs to have rules for both required and not-required cases.

2021-04-09 04:38 UTC, danieldunderfelt commented on src/departure/observedDeparture/createObservedDeparturesTask.ts
> +                  plannedSchemaDepartures?.get(`${dayTypeDef.normalDayType}:${journeyStartTime}`) ||
Yes, that could work as long as it doesn't do any additional fetching!

2021-04-09 04:40 UTC, danieldunderfelt commented on src/executionRequirement/observedExecutionRequirement/observedRequirementUtils.ts
> +      id: combinedUuid,
We don't WANT a new unique uuid! The uuid needs to be the same if the areaRequirement is combined from the same requirements. There was a bug where they would show up double since it generated a new ID every time.

2021-04-09 04:42 UTC, danieldunderfelt commented on src/hfp/HfpStopEventEntity.ts
> +    let odayObj = new Date(parseInt(hfpRow.oday, 10))
Sure, but it's `oday` in the HFP event. I've used `oday` to make clear where it comes from. I'm not opposed to `operatingDate` though!

2021-04-09 04:52 UTC, danieldunderfelt commented on src/hfp/hfpUtils.ts
> +      item.plannedDepartureDateTime!
You make a good point, but the idea behind this function is that it can be fed any sort of "observed" departure, eg. a departure which uses HFP data, and it will spit out a key that identifies the journey. So I would like to keep the option to give it all these types of arguments.

Then you can do this:

```
let observedDepartureKey = createSpecificJourneyKey(observedDeparture)
let hfpRowKey = createSpecificJourneyKey(hfpRow)

let isSameJourney = observedDepartureKey === hfpRowKey
```

If we make separate functions for all arguments, we have a bunch of functions that all do the same thing, just with different types of arguments. I think it's better to have one function that does one thing with different arguments.

Also, these keys should never EVER be parsed in any way, just compared.

2021-04-09 04:54 UTC, danieldunderfelt commented on src/departure/observedDeparture/createObservedDeparturesTask.ts
> +                dayTypeDef.effectiveDayType !== dayTypeDef.normalDayType
We can remove the unused keys yes, but I like the naming "effective/normal" much more than "source/target", which I don't think describes what it happening as well.

2021-04-09 04:57 UTC, danieldunderfelt commented on src/departure/observedDepartureAnalysis/earlyTimingStopDepartureAnalysis.ts
> +      sanctionableValue: timingStopDeparture.observedDepartureDifferenceSeconds + '',
![54xuxl](https://user-images.githubusercontent.com/3145668/114130394-289c0100-9909-11eb-94a9-ba7c20d32db8.jpeg)

2021-04-13 04:58 UTC, danieldunderfelt commented on src/departure/observedDeparture/createObservedDeparturesTask.ts
> +                  plannedSchemaDepartures?.get(`${dayTypeDef.normalDayType}:${journeyStartTime}`) ||
Thinking about it, it should really be done behind an `if` like it is currently.

2021-04-13 05:00 UTC, danieldunderfelt commented on src/hfp/hfpUtils.ts
> +      item.plannedDepartureDateTime!
I'll see what I can do about this when I do further fixes for the HFP data.

2021-04-13 05:13 UTC, danieldunderfelt commented
It wasn't really a part of the 220 card, but I removed the redundant dayType fields.

2021-04-13 07:59 UTC, Divinare commented on src/executionRequirement/observedExecutionRequirement/observedRequirementUtils.ts
> +      id: combinedUuid,
Ah okay I see!

2021-04-13 08:33 UTC, Divinare commented on src/executionRequirement/observedExecutionRequirement/observedRequirementUtils.ts
> +      id: combinedUuid,
Well, to be precise / more clear, i'd say this in comments:

```
// The areaRequirement id needs to be the same if it's combined from the same requirement ids
let areaReqirementId = combineUuids(weekRequirements.map(req => req.id))

  id: areaReqirementId,
```

2021-04-13 08:47 UTC, Divinare commented on src/departure/observedDepartureAnalysis/equipmentTypeDepartureAnalysis.ts
> +      }`,
This required logic seems to be only for equipment type sancationing, not for others right? Maybe it's then acceptable then to not pass it in it's own value e.g.
```
sanctionAmount,
sanctionValue: ...
sanctionTier: ...
```
"sanctionTier", "NORMAL" default, "HIGH"

But yeah maybe can consider this later if other sanction reasons needed a sanctionTier

2021-04-13 08:51 UTC, Divinare commented on src/departure/observedDeparture/createObservedDeparturesTask.ts
> +                  plannedSchemaDepartures?.get(`${dayTypeDef.normalDayType}:${journeyStartTime}`) ||
Well
```
let plannedSchemaRouteDepartures =
                plannedSchemaDepartures?.get(createSchemaDeparturesKey(dayType, journeyStartTime)) || []
```
I think this solution is as efficient as the current one, it doesn't do any additional fetching. If plannedSchemaDepartures is null/undefined, it doesnt call .get

2021-04-13 08:53 UTC, Divinare reviewed
Left some comments

2021-04-13 08:56 UTC, Divinare approved these changes
I would like those minor changes but we can also live without them!

2021-04-13 09:17 UTC, danieldunderfelt commented on src/departure/observedDepartureAnalysis/equipmentTypeDepartureAnalysis.ts
> +      }`,
Yes, only EquipmentType.

2021-04-13 09:20 UTC, danieldunderfelt commented on src/departure/observedDeparture/createObservedDeparturesTask.ts
> +                  plannedSchemaDepartures?.get(`${dayTypeDef.normalDayType}:${journeyStartTime}`) ||
Maybe I don't understand this...

The idea here is to first see if there are departures for the dayType in effect (eg. the exception dayType), and IF THERE ARE NOT, fetch departures for the normal dayType for that day.

2021-04-13 09:22 UTC, danieldunderfelt commented on src/executionRequirement/observedExecutionRequirement/observedRequirementUtils.ts
> +      id: combinedUuid,
Yes, there could always be more comments! :D I'll add it.

2021-04-13 12:42 UTC, Divinare commented on src/executionRequirement/observedExecutionRequirement/observedRequirementUtils.ts
> +      id: combinedUuid,
Well, better would always be to have code be self explanatory... but in this case it's not possible

2021-04-14 08:24 UTC, danieldunderfelt commented on src/executionRequirement/observedExecutionRequirement/observedRequirementUtils.ts
> +      id: combinedUuid,
I mean yes we could name it `createDeterministicUuidFromCombinedUuids` but I think I'll just add the comment.

2021-04-14 08:27 UTC, merged