245 hfp optimization
HSLdevcom/bultti pull request #247
Opened 2021-04-12 09:06 UTC by danieldunderfelt

HFP investigation, optimization and fixes related to tickets https://github.com/HSLdevcom/bultti/issues/245, https://github.com/HSLdevcom/bultti/issues/241, https://github.com/HSLdevcom/bultti/issues/221 and https://github.com/HSLdevcom/bultti/issues/217.

UI PR: 

Main changes:

- Checks which stops to load for each route, loads only stops relevant to Bultti.
- Updates and optimisations for features that use HFP data
- Refactors and updates to HFP functions

2021-04-14 13:28 UTC, Divinare requested changes
Left some minor comments, otherwise LGTM.

Hfp-loading related code start to get clear! That observedDeparturesTask is still confusing, a lot of things were refactored / changed there, this task got a bit too wide I guess.

2021-04-14 13:28 UTC, Divinare commented on src/hfp/hfpUtils.ts
> +export async function createExistingEventsChecker(
createExistingStopEventsChecker?

2021-04-14 13:28 UTC, Divinare commented on src/hfp/hfpUtils.ts
> +    existingEventUuids.push(set)
Interesting, making a set for each million row just in case to prevent memory issues or smth

2021-04-14 13:28 UTC, Divinare commented on src/inspection/inspectionLinks.ts
> +export async function getLinkedFromInspections(inspection: Inspection): Promise<Inspection[]> {
Nit:
```suggestion
export async function getLinkedInspections(inspection: Inspection): Promise<Inspection[]> {
```

2021-04-14 13:28 UTC, Divinare commented on src/inspection/inspectionLinks.ts
> +  let linkedFromInspections = await repo.find({
Nit: could it be like this?
```suggestion
  let linkedInspections = await getRepository(Inspection).find({
```

2021-04-15 03:30 UTC, danieldunderfelt commented on src/inspection/InspectionResolver.ts
> +    inspection.versionStackIdentifier = createStackIdentifier(inspection)
The idea here is to extract the `inspectionDate` stuff from the input object and fetch the inspectionDate with the inspectionId. Then, what's left of the inspectionInput is put into the `assignInspectionInput` var. Then, outside the `if`, the whole `assignInspectionInput` is written to the Inspection entity. For PRE-inspections, this would include everything from the input.

For non-PRE, we still need to assign the rest of the inspectionInput to the entity, there are `name`, `startDate` and `endDate` props that would be ignored if we removed the `merge` row.

I suppose the `InspectionInput` props can be assigned one-by-one, but the current code works so I don't really see a reason to change it.

2021-04-15 03:31 UTC, danieldunderfelt commented on src/queue/queueManager.ts
> +import { DISABLE_CACHE } from '../constants'
Dang, I try to remove these with the webstorm feature but some slip through.

2021-04-15 03:31 UTC, danieldunderfelt commented on src/inspection/inspectionReportsPreCache.ts
> +  if (DISABLE_PRE_CACHE) {
Yes!

2021-04-15 03:33 UTC, danieldunderfelt commented on src/hfp/hfpStorage.ts
> +          (await eventFilter(hfpRow))
No, that's not the point. The eventFilter is instantiated outside the loop, because it sets up a cache map that remembers the result of queries. If it would be instantiated here, there would be no caching since it would be recreated on each loop iteration.

I don't really like passing it down either but it is quite necessary.

2021-04-15 03:35 UTC, danieldunderfelt commented on src/hfp/hfpStopsFilter.ts
> +    if (!hfpEvent.stop || !hfpEvent.route_id || !hfpEvent.direction_id) {
Yes, this is more of a safeguard. Theoretically there could be an object coming it where all fields are `null`, and we don't want those.

2021-04-15 03:37 UTC, danieldunderfelt commented on src/hfp/hfpStopsFilter.ts
> +          routeStops.length === 0 ? false : routeStops.some(stopId => hfpEvent.stop === stopId)
Of course it's a filter! It checks that the HFP event is from a stop that is relevant to Bultti and filters out the ones that are not.

`HfpStopsFilter` is also quite apt, since it filters the HFP rows based on the stop.

I really don't get this comment.

2021-04-15 03:41 UTC, danieldunderfelt commented on .env.production
> +WORKER_CONCURRENCY=1
This config determines how many tasks one worker does concurrently. There are more than one worker yes.

This is a conservative value, and it is just a default. It can also be set in the Gitlab deploy repo. If we monitor the workers and see that they can do multiple tasks at once the number can be increased.

And yes, I also don't want to leave configs that are unused!

2021-04-15 03:42 UTC, danieldunderfelt commented on src/hfp/hfpStorage.ts
>    let container = await getContainer(hfpContainerName)
Well, the Azure library calls it a container...

2021-04-15 03:46 UTC, danieldunderfelt commented on src/hfp/hfpStorage.ts
> +            createdJourney = HfpJourney.createFromHfpRow(hfpRow, blobName)
Yes, this could be very useful to do! Although it won't tell the whole story about missing events, it may tell a part of it.

Card => https://github.com/HSLdevcom/bultti/issues/249

2021-04-15 03:46 UTC, danieldunderfelt commented on src/hfp/hfpUtils.ts
> +export async function createExistingEventsChecker(
No, this just checks that the event isn't already in the database.

And I've removed it completely in the 217 branch :D

2021-04-15 03:47 UTC, danieldunderfelt commented on src/hfp/hfpUtils.ts
> +    existingEventUuids.push(set)
Yes! The Set only supports a certain amount of entries, so I had to split them up into multiple sets.

2021-04-15 03:50 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +export async function getLinkedFromInspections(inspection: Inspection): Promise<Inspection[]> {
This is the reverse of "linked inspections", as this function finds where the `inspection` is linked _from_, hence the name. If you have a better suggestion I will consider it, but "from" is an important word in the name here.

2021-04-15 03:51 UTC, danieldunderfelt commented on src/inspection/inspectionLinks.ts
> +  let linkedFromInspections = await repo.find({
Sure, we can inline the repo creation. But as I said previously, "from" is an important distinction here and it tries to tell you what's going on.

2021-04-15 03:59 UTC, danieldunderfelt commented on src/inspection/inspectionReportsPreCache.ts
> +  if (DISABLE_PRE_CACHE) {
It seems to already be there... maybe I added it yesterday.

2021-04-15 04:18 UTC, danieldunderfelt commented on src/inspection/InspectionResolver.ts
> +    inspection.versionStackIdentifier = createStackIdentifier(inspection)
I simplified the code a bit anyway!

2021-04-15 04:23 UTC, danieldunderfelt commented
I did minor refactors and cleaned up some unused env vars!

About the `observedDeparturesTask`, I refactored it into multiple smaller functions to make it more understandable. There are not really any actual _changes_, just moving code around.

2021-04-15 05:55 UTC, Divinare commented on src/inspection/InspectionResolver.ts
> +    inspection.versionStackIdentifier = createStackIdentifier(inspection)
Yeah now I think it makes more sense!

I misunderstood the code because of this line:
```
    if (inspection.status !== InspectionStatus.Draft) {
      useInspectionInput = pick(inspectionInput, 'name')
    }
```
Thought useInspectionInput would have only 'name' but yea it's only when inspection.status !== InspectionStatus.Draft... Should have read more carefully!

2021-04-15 06:33 UTC, Divinare commented on src/hfp/hfpStorage.ts
> +          (await eventFilter(hfpRow))
Maybe could have a few comments:
```
// Returns a callback that returns a boolean whether given hfpRow is a stop event or not
// Uses cache so this has to created only once
export function createHfpStopsFilter(weekStartDate: Date) {
```

2021-04-15 06:35 UTC, Divinare approved these changes
Maybe could have a few comments:
```
// Returns a callback that returns a boolean whether given hfpRow is a stop event or not
// Uses cache so this has to created only once
export function createHfpStopsFilter(weekStartDate: Date) {
```

2021-04-15 06:45 UTC, Divinare commented on src/inspection/inspectionLinks.ts
> +export async function getLinkedFromInspections(inspection: Inspection): Promise<Inspection[]> {
Ah this one is tough to name!

I came up with:
```getInspectionsLinkedFromInspection()
...
let inspectionsLinkedFromInspection = await repo.find({
```

2021-04-15 09:15 UTC, Divinare commented
Hfp-loading seems to work!

2021-04-15 09:15 UTC, merged