221 hfp event improvement
HSLdevcom/bultti pull request #250
Opened 2021-04-15 05:13 UTC by danieldunderfelt

(Merge https://github.com/HSLdevcom/bultti/pull/247 first)

UI PR: 

Further improvements to HFP processes in the quest to get correct report data and not so many unobserved departures.

- Remove existing event checker, was causing some of the problems. If an event already exists in the database it is not duplicated anyway thanks to primary keys and the use of `onConflict('DO NOTHING')` in the insert query.
- Download HFP blobs to a temp file first instead streaming the Azure download directly through the parser into the database.
- Remove journeyKey prop from both HFP entities, it was unused. Also remove other unused bits and pieces.
- Include ARR event in HFP import and update event type selection logic for arrival events

2021-04-15 13:38 UTC, Divinare requested changes
Found some minor code quality things, otherwise LGTM!

Still need to test hfp loading with this new code.

2021-04-15 13:38 UTC, Divinare commented on src/hfp/hfpStorage.ts
> -          !checkEventUuidExists(hfpRow.uuid) &&
This was for checking if the data hfp row is already downloaded? And now we can live without it because:
```
.createQueryBuilder()
.onConflict('DO NOTHING')
```
does nothing if it tries to insert duplicated data, am I right?

2021-04-15 13:38 UTC, Divinare commented on src/util/moduleValueUtil.ts
> +export function getModuleValue<ValueType>(name: string, initialValue: ValueType): ValueType {
Hmm, havent used term moduleValue before... 
```
getSingletonObject()
cleanupSingletonObject()
```
would these work better?

Well, not sure if I like the solution because now one has to call cleanupFilterCache() with the right key.

Performance wise i don't think it adds much. You get rid of the map in memory a bit earlier than before when you call cleanupModuleValue()

Mayyybe the best would be to extract "eventFilterCache" out from eventFilter and then pass that cache down the props, everyone understands that cache has to be declared early.

But i'm also not insisting to replace this solution... in the end both of them do work at least.

2021-04-15 13:44 UTC, Divinare commented on src/hfp/hfpStorage.ts
> -          !checkEventUuidExists(hfpRow.uuid) &&
Ah, this was already mentioned in the comments so yea, that's nice to get rid of checkEventUuidExists()!

2021-04-16 03:24 UTC, danieldunderfelt commented on package.json
> +    "@azure/storage-blob": "^12.5.0",
This is just what comes by default. I get the reasoning why pinning the version is a good precaution, but I've never had anything break because of the ^ (that I can remember) so I don't worry about it too much.

You can remove them if you want but I wouldn't bother.

In this case I tried installing the latest version but it didn't help.

2021-04-16 03:24 UTC, danieldunderfelt commented on src/hfp/hfpStorage.ts
>  let stopEventsBlobsPrefix = 'csv/StopEvent/'
Yes, good point.

2021-04-16 03:26 UTC, danieldunderfelt commented on src/hfp/hfpStorage.ts
> +  let container = await getContainer(hfpContainerName)
Maybe? "Container" is what the Azure library calls it, so this code can be understood by reading the Azure library docs.

2021-04-16 03:31 UTC, danieldunderfelt commented on src/hfp/loadHfpForDate.ts
> +  let loadBlobData = await createJourneyEventBlobStreamer(date, eventFilter)
Yes, these could be better, but I'm not completely happy with the suggestions either. I'll think about better names for these.

2021-04-16 03:57 UTC, danieldunderfelt commented on src/hfp/loadHfpForDate.ts
> +    let blobPromise = loadBlobData(blobPath, onData)
Yes, good point. I usually try to define functions before they are used, but due to using the `function` keyword it of course doesn't matter. Readability comes first.

2021-04-16 04:03 UTC, danieldunderfelt commented on src/hfp/loadHfpForDate.ts
>    flushBatches()
logTime is a dev utility that I use often, but I try to clean it up because it should usually not be left in (like console.log). So no, it is absolutely not only called here.

Generally useful utilities are good to have even if they are only called from one place.

2021-04-16 04:06 UTC, danieldunderfelt commented on src/hfp/hfpStorage.ts
> -          !checkEventUuidExists(hfpRow.uuid) &&
Yes, it was kind of a double check and performance improvement, since skipping the row is faster than dragging it all the way to the insert function. But it did cause problems in the form of missing events, and I'm not sure how much performance it really contributed, so I got rid of it.

2021-04-16 04:21 UTC, danieldunderfelt commented on src/util/moduleValueUtil.ts
> +export function getModuleValue<ValueType>(name: string, initialValue: ValueType): ValueType {
Hmm... it's not really a singleton though. The idea here is to have way to declare values "in the module scope", eg. in a file outside any other function, that can be cleaned up. The alternative is having a value that you CANNOT clean up, and if it's a map with a large amount of data, it can eat some memory.

I'm not a fan of having a cache object specifically for some function that is declared separately from the function. That's why I like the "creator" pattern where a factory function declares values that don't change in the outer scope and returns a function that can be called repeatedly and make use of the value in the outer scope.

This is not for performance, it is to prevent memory leaks. Calling the cleanup function means you CAN get rid of the value, vs not being able to get rid of it.

Maybe "moduleValue" is not the best name, but this is meant to be a better solution for values declared in the module scope and I wanted the name to reflect that.

Also, `cleanupFilterCache` does not take a key. No one else but the module that set up the moduleValue needs to know about the key if it defines its own cleanup function. Using a string key prevents the need for an additional module-scoped value to keep track of cleanup functions or similar alternative solutions.

2021-04-16 04:30 UTC, danieldunderfelt commented on src/hfp/loadHfpForDate.ts
> +  let loadBlobData = await createJourneyEventBlobStreamer(date, eventFilter)
They shall be named `createHfpBlobFileReader` and `readBlobFile`.

2021-04-16 04:36 UTC, danieldunderfelt commented
Fixes and updates done!

2021-04-16 04:37 UTC, danieldunderfelt commented on src/hfp/hfpUtils.ts
> -  }
Yes, you made a good point that it wasn't used for anything except HfpRows!

2021-04-16 05:20 UTC, Divinare commented on src/hfp/loadHfpForDate.ts
> +  let loadBlobData = await createJourneyEventBlobStreamer(date, eventFilter)
Yeah those are better!

2021-04-16 05:45 UTC, Divinare commented on src/hfp/loadHfpForDate.ts
>    flushBatches()
Ah I ment ```flushBatches()```, not the logTime func. Yeah, I could've used `flushBatches()` in my comment, it's a bit unclear to point out something in old code ^^

2021-04-16 06:19 UTC, Divinare commented on src/util/moduleValueUtil.ts
> +export function getModuleValue<ValueType>(name: string, initialValue: ValueType): ValueType {
Hmm, this is an interesting topic. After reading a bit of memory leaks in javascript, I think the previous solution wouldn't cause memory leaks because JS is a "garbage collected language"

Mainly the causes to memory leaks were:
1: Accidental global variables
2: Forgotten timers or callbacks
3: Out of DOM references
4: Closures
It says though: "Although Garbage Collectors are convenient they come with their own set of trade-offs. One of those trade-offs is nondeterminism. In other words, GCs are unpredictable. It is not usually possible to be certain when a collection will be performed."

So I guess it's fine to use this solution that it gets cleaned up immediately. And we get to use creator pattern!

One risk there is tho, if you return somehow before calling cleanupFilterCache() with the key, data will be kept in memory until backend restarts.... So i'd say it comes with a drawback.

Still not fan of ModuleValueUtil name, I see this like globalState in frontend. Don't know what would be better name, globalValueUtil & getGlobalValue?

2021-04-16 06:22 UTC, Divinare commented
Tested hfp loading:

I removed inspectionDate range 11 Jan 2021 - 17 Jan 2021, added it back and loaded hfp-data from it yesterday with this new code, results were:
35677232	./jore-db
select COUNT(*) from journey;
418568
select COUNT(*) from stop_event;
2957874

After removing 11 Jan 2021 - 17 Jan 2021 (removal of inspectionDates didn't affect the data btw), I loaded hfp-data again, now I have:
select COUNT(*) from journey;
418819
select COUNT(*) from stop_event;
2957874
35660952	./jore-db

--> Seems like stop_event count was the same! But I got ~250 additional journeys. This should be investigated.

2021-04-16 07:31 UTC, merged