WIP 229 test data
HSLdevcom/bultti pull request #267
Opened 2021-04-28 05:05 UTC by danieldunderfelt

Issue: https://github.com/HSLdevcom/bultti/issues/229

UI PR:

Generate test data for pre and post inspections. Check the TEST_DATA document for details and usage instructions.

- Test data generators and DB functions
- AdminResolver to insert and remove test data
- Fix and use deterministic UUID functions
- Generate test departure blocks as downloadable files
- WIP: hide test data for normal users

2021-04-29 14:16 UTC, Divinare requested changes
Left some comments, otherwise LGTM! This is really helpful to get predictable testing data for E2E tests.

2021-04-29 14:16 UTC, Divinare commented on src/inspection/InspectionDateEntity.ts
> +  isTest: boolean
Hmm, could we use operatorId of "Bultin Testiliikennöitsijä" to see whether inspection is used for testing purposes only?

2021-04-29 14:16 UTC, Divinare commented on src/inspection/InspectionDateEntity.ts
> +  isTest: boolean
Btw, for some reason this "isTest" isn't getting generated into Inspection table in my local db

2021-04-29 14:16 UTC, Divinare commented on src/test/TEST_DATA.md
> +It is good practise to first delete test data if you are changing the generator code. While JORE test data is removed by a common value ("bulttitest"), Bultti and HFP data uses the ID field which is
Hmm, indeed removing old test data is a must before deploying new changed test data. Sadly we can't ensure that devs remember to do that... Maybe add a reminder of this somewhere?

2021-04-29 14:16 UTC, Divinare commented on src/util/deterministicUuid.ts
> +export function combineUuids(uuids: string[]) {
Maybe the file name could be "uuidUtils" (and not deterministicUuid)?

2021-04-29 14:16 UTC, Divinare commented
I would say that we should to hardcode contract as well. Because in E2E tests we need to expect some values that are calculated based on contract information and we want that the values we expect are always the same.

2021-04-30 03:13 UTC, danieldunderfelt commented on src/AdminResolver.ts
> +    await insertTestData(testData)
"Insert" is better here IMO. It's _inserting_ the _test data_ given to it.

2021-04-30 03:13 UTC, danieldunderfelt commented on src/AdminResolver.ts
> +// Common resolver for admin stuff that doesn't fit elsewhere.
Myeah. Maybe DevResolver?

2021-04-30 03:16 UTC, danieldunderfelt commented on src/test/TEST_DATA.md
> +It is good practise to first delete test data if you are changing the generator code. While JORE test data is removed by a common value ("bulttitest"), Bultti and HFP data uses the ID field which is
It's here, in the documentation! But maybe it could also be added on the admin (or dev) page.

2021-04-30 03:17 UTC, danieldunderfelt commented on src/AdminResolver.ts
> +  async generateTestBlockDepartures(
Sure, but it is also mentioned in the documentation.

2021-04-30 03:18 UTC, danieldunderfelt commented on src/AdminResolver.ts
> +      await notifySubscribers(inspection, UpdateType.REMOVE, user || undefined)
Not for test inspections. I'll update this!

2021-04-30 03:22 UTC, danieldunderfelt commented on src/common/view/Index.js
> -      <p>Please use the proper UI!</p>
Yeah... I had planned to use this stuff for admin stuff but the lack of cookies (as opposed to transitlog-server) made it difficult.

2021-04-30 03:23 UTC, danieldunderfelt commented on src/inspection/InspectionDateEntity.ts
> +  isTest: boolean
Did you get this resolved? It worked for me last time I checked.

2021-04-30 03:24 UTC, danieldunderfelt commented on src/util/deterministicUuid.ts
> +export function combineUuids(uuids: string[]) {
Well all functions are for cresting deterministic UUID's, so i think the name is apt.

2021-04-30 03:29 UTC, danieldunderfelt commented
> I would say that we should to hardcode contract as well. Because in E2E tests we need to expect some values that are calculated based on contract information and we want that the values we expect are always the same.

We still need a test_contract.toml for E2E testing the contract features, so the test data can make use of this as well. Then we only need to have test contract values in one place instead of two. I also want the test data to mirror real data and usage as close as possible, and using the normal parsing functions for a toml file is a part of this.

2021-04-30 05:17 UTC, Divinare commented on src/AdminResolver.ts
> +    await insertTestData(testData)
Yeah, both are OK. Have just seen seed used inserting test data, but insert is it's fine as well

2021-04-30 05:19 UTC, Divinare commented on src/AdminResolver.ts
> +// Common resolver for admin stuff that doesn't fit elsewhere.
Yeah DevResolver is a good name!

2021-04-30 05:22 UTC, Divinare commented on src/util/deterministicUuid.ts
> +export function combineUuids(uuids: string[]) {
Ah okay, then it's fine!

2021-04-30 05:25 UTC, Divinare commented
Yeah true, we should make a static test_contract.toml that is committed in the repo that has dummy values just for testing. Didn't think of getting parsers tested through this way!

Just have to remember moving this .toml to docker container once we make it.

2021-04-30 05:44 UTC, Divinare commented on src/inspection/InspectionDateEntity.ts
> +  isTest: boolean
Ah nvm, this one is OK

2021-04-30 06:24 UTC, Divinare approved these changes
LGTM!

2021-04-30 10:20 UTC, merged