188 split Inspection into Pre and Post Inspections
HSLdevcom/bultti pull request #274
Opened 2021-05-03 12:28 UTC by danieldunderfelt

Issue: https://github.com/HSLdevcom/bultti/issues/188

UI PR: WIP

- Create Pre and Post Inspection entities
- Create base Inspection entity for these to extend from
- Also split Resolvers
- Create Common and Base Inspection resolvers
- LOTS of changes related to this

Recommended to have truncated most tables in the DB before running this branch. You can leave procurementUnit, user and contracts.

2021-05-04 13:56 UTC, Divinare requested changes
Left some comments. Still haven't tested yet (waiting for UI PR to be finished)

Nice work anyways!

2021-05-04 13:56 UTC, Divinare commented on src/report/reportUtils.ts
> +export function createReportCacheKey<InspectionType extends Inspection>(
Is
```
InspectionType extends Inspection
```
Needed?

```suggestion
export function createReportCacheKey(
  inspection: Inspection,
  reportName
) {
```
Can it be done just like this? I mean that generic type declaration <...> is not used at least here

2021-05-04 13:56 UTC, Divinare commented on src/report/reportUtils.ts
> +export async function createExcelReport<InspectionType extends Inspection>(
Just curious, why wouldn't this be good?
```
export async function createExcelReport(
  inspectionId: string,
  createExcelData: (inspection: Inspection) => Promise<WorkBook | undefined>
): Promise<WorkBook | undefined> {
  let inspection: Inspection = await getInspectionById(inspectionId)
  return createExcelData(inspection)
}
```
(need to make getInspectionById() to return Inspection to get this work)

2021-05-05 04:42 UTC, danieldunderfelt commented on src/inspection/PreInspectionEntity.ts
> +  season: Lazy<Season>
They need to be attached to the concrete entity, either PreInspection or PostInspection, because they are now two different tables.

Ideally they would be on InspectionEntity, yes, but I don't think it is possible.

2021-05-05 05:01 UTC, danieldunderfelt commented on src/inspection/PreInspectionEntity.ts
> +  inspectionErrors?: ValidationErrorData[]
I also want as much as possible in the abstract Inspection entity, and there is a very good reason for each field to be in the concrete classes.

For userRelations, the reason is the same as above that as it is a database relation, it needs to be on the concrete class that has the database table. For `inspectionErrors`, the reason is type-graphql errors when it is not found on the concrete class.

2021-05-05 05:03 UTC, danieldunderfelt commented on .eslintrc.js
> +    '@typescript-eslint/no-unused-vars': 0,
type-graphql recommends uses "unused" vars in the decorators for readability (eg. `@Query(returns => Inspection)`), and I like them. I don't want them to be warnings or errors. Webstorm unused var highlighting is enough IMO.

2021-05-05 05:05 UTC, danieldunderfelt commented on src/executionRequirement/observedExecutionRequirement/observedRequirementUtils.ts
> +    await ObservedEmissionClassRequirement.pruneDanglingValues()
I don't think it's because of the structure. Cascades are tricky, and it is important to ensure these are actually removed.

2021-05-05 05:07 UTC, danieldunderfelt commented on src/report/reportUtils.ts
> +export function createReportCacheKey<InspectionType extends Inspection>(
It's a type constraint. If it would be just `Inspection` you couldn't pass Pre or PostInspections to this function. It is "used" just because it exists.

2021-05-05 05:10 UTC, danieldunderfelt commented on src/report/reportUtils.ts
> +export function createReportCacheKey<InspectionType extends Inspection>(
The idea is that it is a type constraint, but now that I tested, just `inspection: Inspection` without the generic thing seems to work just as well! I was under the impression that this needed to be wired up with generics.

2021-05-05 05:13 UTC, danieldunderfelt commented on src/report/reportUtils.ts
> +export async function createExcelReport<InspectionType extends Inspection>(
Well, I thought I needed to use generics to enforce type constraints like this, but apparently I don't.

2021-05-05 05:23 UTC, Divinare commented on .eslintrc.js
> +    '@typescript-eslint/no-unused-vars': 0,
Ah if type-graphql needs them, it's then to not warn

2021-05-05 06:03 UTC, Divinare approved these changes

2021-05-05 07:11 UTC, merged