275 update procurement unit map
HSLdevcom/bultti pull request #276
Opened 2021-05-07 07:23 UTC by danieldunderfelt

Closes https://github.com/HSLdevcom/bultti/issues/275

UI PR

- Clear up procurement unit fetching and add some comments
- Update contract -> procurement unit map creation
- Update ContractManager to fetch contracts by date and from linked pre-inspections
- Update contract manager method calls to use date

2021-05-07 12:27 UTC, Divinare requested changes
ContractManager makes now sense!

Couldn't test though, not sure if it's just for me but it doesn't let me create preInspection (yes, I pulled have the latest changes :P)

![create_preInspection](https://user-images.githubusercontent.com/1419296/117449341-8a6f7b00-af48-11eb-979c-8ea0b17e60e7.png)

2021-05-07 12:27 UTC, Divinare commented on src/contract/ContractManager.ts
> + * used to select the correct contract to use.
Also I was thinking of making the date optional and in the start of the functions, check if given preInspection + date, you could throw an error (perhaps I'm overthinking)

2021-05-07 12:27 UTC, Divinare commented on src/contract/ContractManager.ts
> +    if (procurementUnitId.length < 36) {
Not really a fan of supporting both .id and .procurementUnitId if not have to

2021-05-10 06:26 UTC, danieldunderfelt commented on src/contract/ContractManager.ts
> +    if (procurementUnitId.length < 36) {
Yeah, well, departures from JORE only have the JORE ID (kohtunnus) and it has to be mapped to Bultti Procurement Unit UUID at some point. This is a logical place to do so and it is nicely invisible to the caller of ContractManager methods.

2021-05-10 06:32 UTC, danieldunderfelt commented on src/contract/ContractManager.ts
> + * used to select the correct contract to use.
Good suggestion! I can expand on the comment further.

2021-05-12 03:55 UTC, merged