271 fix sanction report percentages
HSLdevcom/bultti pull request #280
Opened 2021-05-13 10:46 UTC by Divinare

Closes https://github.com/HSLdevcom/bultti/issues/271

2021-05-19 10:48 UTC, Divinare commented on src/report/postInspectionReports/sanctionSummaryReport.ts
> +      code: 'EOAT',
This maybe should be made as a constant value and add it somewhere...
However there was this other place as well:
```
    let sanctionAmount = await contractManager.getRuleValue({
      code: 'EAO',
      procurementUnitId: unitExecutionItem.procurementUnitId,
      defaultValue: 0,
    })
```

2021-05-19 11:03 UTC, danieldunderfelt requested changes
Looks good, but there are some comments.

2021-05-19 11:03 UTC, danieldunderfelt commented on src/sanctioning/SanctionEntity.ts
> +  sanctionableKilometers: number // TODO: rename as totalUnitKilometers?
No, this is the sanctionable kilometers sum, not the total kilometers in the unit.

2021-05-19 11:16 UTC, Divinare commented on src/sanctioning/SanctionEntity.ts
> +  sanctionableKilometers: number // TODO: rename as totalUnitKilometers?
Ah yeah... This was an old comment. No change needed

2021-05-19 11:26 UTC, Divinare commented on src/report/postInspectionReports/sanctionSummaryReport.ts
> +  sanctionAmount: number // TODO: rename as sanctionPercentage?
SanctionAmountPercentage is a good name for describing what it is!

Well... One option would be to get rid of this variable and use it to form column names in backend? If it's only use to give column a percentage: e.g. "Kaluston yli-ikäisyys 10%"

2021-05-20 03:47 UTC, danieldunderfelt commented on src/report/postInspectionReports/sanctionSummaryReport.ts
> +      code: 'EOAT',
EOAT is the upper age limit (threshold), while EAO is the sanction amount.

2021-05-20 10:36 UTC, Divinare commented on src/report/postInspectionReports/sanctionSummaryReport.ts
> +    let sanctionUnitReasonGroups = groupBy(
True, now when you say. They are actually:
SanctionUnitReasonAmountGroups, but it can be shortened as SanctionReasonAmountGroups

2021-05-21 06:22 UTC, merged