3 equipment defect sanctions
HSLdevcom/bultti pull request #285
Opened 2021-05-19 10:29 UTC by danieldunderfelt

Issue: https://github.com/HSLdevcom/bultti/issues/283

UI PR:

Equipment Defect sanctioning and JOLA setup. Also resolver to enable showing JOLA rows in the UI.

- Equipment defect sanctioning setup
- JOLA connection setup
- JOLA response filtering and formatting
- Resolver to make the data queryable from the UI

2021-05-19 14:01 UTC, Divinare requested changes
Left some small code quality proposals. This seems to be a good start for equipment defect sanctioning! Good job.

2021-05-20 02:18 UTC, danieldunderfelt commented on src/equipmentDefect/EquipmentDefectEntity.ts
> +  concludedDate: string | null
It won't necessarily be repaired though! As I understood it, there may be cases where the JOLA "ticket" can be closed without any fixes being done. "Concluded" covers this possibility as well.

2021-05-20 02:20 UTC, danieldunderfelt commented on src/equipmentDefect/equipmentDefectUtils.ts
> +  let weekStartDate = getDateString(startOfISOWeek(startDateObj))
It's just a precaution.

2021-05-20 02:21 UTC, danieldunderfelt commented on src/equipmentDefect/equipmentDefectUtils.ts
> +  let validStatuses = Object.keys(jolaStatusToEnumMap)
It just maps the status string from JOLA into an enum. It doesn't have an opinion on if it's valid or not.

2021-05-20 02:22 UTC, danieldunderfelt commented on src/equipmentDefect/equipmentDefectUtils.ts
> +  let validPriorities = ['Korjattava', 'Vaarallinen']
Actually yes, this should be moved outside the function in this case.

2021-05-20 02:24 UTC, danieldunderfelt commented on src/equipmentDefect/equipmentDefectUtils.ts
> +  let jolaRows = await getJolaRows()
It's already really fast, and I think having filtering logic in the code is better and more flexible than putting it in the URL. I'm not sure if the Louhin URL filters can even accommodate the date filtering logic we have.

Also there is no field for operator in the data.

2021-05-20 02:25 UTC, danieldunderfelt commented on src/jore/JoreDataSource.ts
> +          -- TODO: Ensure that these are the correct dates to use for procurement unit queries
Yes.

2021-05-20 02:27 UTC, danieldunderfelt commented on src/sanctioning/collectEquipmentDefectSanctions.ts
> +export async function collectEquipmentDefectSanctions(
No, I will continue on this branch. I try to cut PR's for this more often so everything won't come at once, so there is bound to be some unfinished pieces here and there for other parts of the equipment defect sanctioning. I ask that you focus on the topic of the PR while reviewing.

2021-05-20 02:30 UTC, danieldunderfelt commented on src/util/isBetween.ts
> +export function compareVal(val: ValueType = 0): number {
I think it makes perfect sense, but it could also be more descriptive, yes. Maybe `createCompareValue`? It's not a getter.

2021-05-20 06:05 UTC, Divinare commented on src/equipmentDefect/EquipmentDefectEntity.ts
> +  concludedDate: string | null
I see. Maybe just "conclusionDate" would still be a bit better?

2021-05-20 06:08 UTC, Divinare commented on src/equipmentDefect/equipmentDefectUtils.ts
> +  let validStatuses = Object.keys(jolaStatusToEnumMap)
Okay if it's all of the enums then OK. I was just thinking if jolaStatusToEnumMap had only the valid statuses because all of it's keys were mapped into validStatuses

2021-05-20 06:16 UTC, Divinare commented on src/equipmentDefect/equipmentDefectUtils.ts
> +  let jolaRows = await getJolaRows()
Okay so we shall trust that the query is fast in the future as well. If it gets slow, we can add query params (well, maybe could add a hint "// if the query gets slow, you can add start and end date filters to the query")

2021-05-20 06:18 UTC, Divinare commented on src/util/isBetween.ts
> +export function compareVal(val: ValueType = 0): number {
createCompareNumber? To indicate it's used to get a number out of given value. It's better than just compareVal

2021-05-20 06:20 UTC, Divinare commented on src/util/isBetween.ts
> +export function compareVal(val: ValueType = 0): number {
Okay I see you used "createNumberCompareValue" - i'm fine with that!

2021-05-20 07:41 UTC, danieldunderfelt commented on src/jore/JoreDataSource.ts
> +          -- TODO: Ensure that these are the correct dates to use for procurement unit queries
The dates are probably fine so I removed this TODO.

2021-05-20 07:43 UTC, danieldunderfelt commented on src/equipmentDefect/equipmentDefectUtils.ts
> +  let jolaRows = await getJolaRows()
Maybe, but as I said I'm not sure if the date filtering logic can be done in the URL. Our Datarangers contact also promised that fetching would be quick so I don't see this being a problem.

2021-05-20 07:45 UTC, danieldunderfelt commented on src/equipmentDefect/equipmentDefectUtils.ts
> +  let validStatuses = Object.keys(jolaStatusToEnumMap)
I haven't seen other statues than this in the response. Filtering based on these keys is a precaution and communicates to future devs which statuses Bultti handles.

2021-05-20 07:46 UTC, danieldunderfelt commented on src/equipmentDefect/EquipmentDefectEntity.ts
> +  concludedDate: string | null
It's a toss-up. I went with "concluded" here, "conclusion" doesn't give any more or less value.

2021-05-20 11:32 UTC, Divinare approved these changes

2021-05-21 06:26 UTC, merged