45 OMM departure blocks
HSLdevcom/bultti pull request #319
Opened 2021-06-03 12:13 UTC by danieldunderfelt

Closes #45 

Integrate departure blocks from OMM over the OMM api. Replaces previous departure block feature.

- Create test data response for departure blocks
- Fetch departure blocks from the OMM api
- Salvage csv parse and OperatorBlockDeparture entity creation from old feature and use it for this one
- Remove OperatorBlockDeparture entity from Typeorm and db
- Cache departure blocks result

For local development and testing, ask the OMM api connection details from me and set them in your own env file, then open a tunnel through Bastion.

2021-06-04 13:41 UTC, Divinare requested changes
Code review done. Still have to test loading block files locally once Jore import finishes. For some reason everything under jore schema disappeared on the first try.

Also got a couple of errors (not sure why):
```
TypeError: Cannot read property 'id' of null
    at /home/joe/HSL/bultti/bultti/src/departure/departureBlock/departureBlocksOMMDataSource.ts:362:18
```

```
insert or update on table "equipment_catalogue" violates foreign key constraint "FK_280bf727c4b16bb363987dffe9e"
```

2021-06-04 13:41 UTC, Divinare commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +        !ommItem?.exceptionDate && ommItem.validOnDates.some(validDate => validDate === dateStr)
```suggestion
        ommItem.validOnDates.some(validDate => validDate === dateStr)
```

I think we should let departure blocks through that are both exceptionDate=false and exceptionDate=true. Isn't it user's responsibility to choose a week that has no exception dates? (This will be done in part 2 of this task)

2021-06-04 13:41 UTC, Divinare commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +    if (normalDayOmmItem) {
Shouldn't departure blocks for inspection date should always be found? I think UI part 2 of this task should ensure that user can only select those weeks where data is going to be found
```
else {
     throw new ApolloError(`No departure blocks found for date: ${dateStr}`)
}
```

2021-06-04 13:41 UTC, Divinare commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +    let departureEntity = await OperatorBlockDeparture.createEntityFromSource(
I wish OperatorBlockDeparture had vehicleId, we wouldn't then have to create Equipment (equipmentForBlock) here, just assign
departureEntity.vehicleId = dep.vehicle_id

2021-06-04 13:41 UTC, Divinare commented on src/test/createTestBlockFiles.ts
> +    blockFileObj.blockFile = Buffer.from(csvString, 'utf8').toString('base64')
Why is it encoded as base64?

2021-06-04 13:41 UTC, Divinare commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +  dayType: string
Maybe add a comment:
dayType: string // 1, 2, 3, ... where "1" = Monday, "2" = Tuesday etc.

2021-06-04 13:41 UTC, Divinare commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +  validOnDates: string[]
Maybe add a comment:
// List of date strings (dd.MM.yyyy) when this blockfile is valid

2021-06-04 13:41 UTC, Divinare commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +      ({ updatedAt }) => parse(updatedAt, 'dd.MM.yyyy HH:mm:ss.SSS', new Date()).getTime(),
I think dd.MM.yyyy could be saved as a constant value, at constants.ts below // OMM add perhaps:
OMM_BLOCK_FILE_DATE_FORMAT = 'dd.MM.yyyy'

2021-06-07 04:47 UTC, danieldunderfelt commented on src/departure/departureBlock/OperatorBlockDepartureResolver.ts
> +  async inspectionDepartureBlocks(
I don't really think this needs to be clearer. This returns the departure blocks used in the inspection, and there are no other departure blocks than Operator Departure Blocks. So the distinction is redundant. "Operator" could also be dropped from the entity name.

OperatorBlockDeparture entities are both GraphQL and Typeorm entities. The GraphQL part is for showing the departure block rows in the UI yes.

2021-06-07 04:49 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +  let invalidOmmConnectionDetails = Object.entries({
I wouldn't think too much about naming variables as long as it's good enough, which I think this one is.

Yes, I hope it is useful!

2021-06-07 04:50 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +   * ssh -L 9000:185.252.116.142:11314 52.174.184.35
I wanted to provide a quick command for other devs to just copy and paste! But maybe this is the wrong place.

2021-06-07 04:53 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +        !ommItem?.exceptionDate && ommItem.validOnDates.some(validDate => validDate === dateStr)
The pre-inspection does not currently take exception dates into account for wither block or JORE departures. When/if we change it so that it does, this filter should be removed. This should probably be done in part 2, but it is not that important as long as it is OK that exception dates are not taken into account.

2021-06-07 04:54 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +    if (normalDayOmmItem) {
Yes, they should. But there could be connection problems etc. Throwing an error here is probably a good idea!

2021-06-07 05:08 UTC, danieldunderfelt commented on src/test/createTestBlockFiles.ts
> +    blockFileObj.blockFile = Buffer.from(csvString, 'utf8').toString('base64')
To enable the file to be downloaded in the UI. But this is for old blockfiles, it won't be needed when the departure blocks come from OMM.

2021-06-07 05:09 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +  dayType: string
A comment doesn't hurt of course, but the dev should really be familiar with the OMM response.

2021-06-07 05:10 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +      ({ updatedAt }) => parse(updatedAt, 'dd.MM.yyyy HH:mm:ss.SSS', new Date()).getTime(),
Maybe, but there is also value in seeing the format of the date directly here in the code.

2021-06-07 05:16 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +    let departureEntity = await OperatorBlockDeparture.createEntityFromSource(
Is the comment in the wrong place? I don't see the context you are referring to.

2021-06-07 05:19 UTC, danieldunderfelt commented
Review fixes done!

2021-06-07 05:42 UTC, Divinare commented on src/departure/departureBlock/OperatorBlockDepartureResolver.ts
> +  async inspectionDepartureBlocks(
I see it confusing that sometimes there is "departure block" and sometimes "block departures" but it always mean the same data? Even in OPERATOR_BLOCK_DEPARTURE.md it says  "block departure"  and "departure block" right after that. I thought OperatorDepartureBlock is a different thing that BlockDeparture that's why I left this comment

2021-06-07 05:52 UTC, Divinare commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +  let invalidOmmConnectionDetails = Object.entries({
I thought my proposal was a bit better

2021-06-07 09:04 UTC, Divinare commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +    let departureEntity = await OperatorBlockDeparture.createEntityFromSource(
Hmm yes, the comment was confusing and wrong. I tried to mean that createDepartureBlockEntities() is pretty long as it also creates Equipment, maybe it would be cleaner to extract Equipment creation to it's own method and call it inside createDepartureBlockEntities()?

2021-06-07 09:05 UTC, Divinare commented on src/test/createTestBlockFiles.ts
> +    blockFileObj.blockFile = Buffer.from(csvString, 'utf8').toString('base64')
Now they come from OMM so should encofing be removed?

2021-06-07 09:08 UTC, Divinare commented on src/test/createTestBlockFiles.ts
> +    blockFileObj.blockFile = Buffer.from(csvString, 'utf8').toString('base64')
"Generate test departure blocks" button and code related to that could be removed?

2021-06-07 09:10 UTC, danieldunderfelt commented on src/test/createTestBlockFiles.ts
> +    blockFileObj.blockFile = Buffer.from(csvString, 'utf8').toString('base64')
Yes, I'll remove those from the UI. Maybe also this file...

2021-06-07 09:45 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +    let departureEntity = await OperatorBlockDeparture.createEntityFromSource(
I see! Yes, you are right, it is pretty long. I copied it directly from the previous departure block feature. I'll try to extract the equipment stuff, but I won't spend too much time as it works as it is already.

2021-06-07 10:23 UTC, danieldunderfelt commented on src/departure/departureBlock/departureBlocksOMMDataSource.ts
> +  let invalidOmmConnectionDetails = Object.entries({
When it comes to naming variables everyone will have different opinion on what is better, and usually it is mostly because it is their own idea. Unless the name is actually bad or the reviewer truly doesn't understand what it means, I don't think we should place too much focus on coming up with alternative names for variables, we'd get nothing else done.

2021-06-07 10:29 UTC, danieldunderfelt commented on src/departure/departureBlock/OperatorBlockDepartureResolver.ts
> +  async inspectionDepartureBlocks(
Yes, I see. This has been challenging to name. A "departure block" technically means the _series_ of departures a vehicle operates one after another, but Bultti deals with rows of data so the meaning has become "one row of the departure block", or "departure block" for short. Or "block departure" which is actually slightly better. OperatorDepartureBlock was one of the first entities I made in Bultti, so the name is maybe a bit redundant.

2021-06-07 13:47 UTC, Divinare approved these changes
Approving, tested that it works with the final changes. Great work!

2021-06-08 03:12 UTC, merged