289 unit contract map fixes
HSLdevcom/bultti pull request #329
Opened 2021-06-07 08:38 UTC by danieldunderfelt

Closes #289 

UI PR: 

Update procurement unit contract map feature so that the map updates when the inspection is updated. Also generate a new map instead of clearing it when the inspection is rejected.

This PR also fixes an issue where post-inspection data is not removed when rejecting it that I noticed along the way.

2021-06-10 13:23 UTC, Divinare requested changes
Left some comments, havent tested yet

2021-06-10 13:23 UTC, Divinare commented on src/inspection/validateInspection.ts
> +  if (!validateContractsForInspectionDate(date, contractMapIds)) {
This one is pretty smart validation. Isn't it so that if an inspection is made, the contract dates can still made until the preInspection is being put to IN_PRODUCTION. Now this validation ensures that the contracts are still within inspection date range.

2021-06-10 13:23 UTC, Divinare commented on src/inspection/validateInspection.ts
> +      end: getDateObject(contract.endDate),
Shouldnt it be like this:
```
let checkInterval = { start: inspectionStartDate, end: inspectionEndDate }

    return areIntervalsOverlapping(checkInterval, {
      start: getDateObject(contract.startDate),
      end: getDateObject(contract.endDate),
    })

```

Contract is OK if it overlaps inspectionStartDate - inspectionEndDate time range?

2021-06-11 03:15 UTC, danieldunderfelt commented on src/inspection/validateInspection.ts
> +      currentContracts.some(contract => contract.id === unitAssignedContract)
Indeed this should not happen, but it may if the contractUnitMap gets out of sync somehow. Not that I have noticed it!

2021-06-11 03:19 UTC, danieldunderfelt commented on src/inspection/validateInspection.ts
> +      end: getDateObject(contract.endDate),
Pre-inspection periods are one week, and the contract can't change in the middle of the week. So if we check the start of the inspection week, it is enough!

Post-inspection dates are not checked with this since they get their inspections through their linked pre-inspections.

2021-06-11 03:23 UTC, danieldunderfelt commented on src/procurementUnit/procurementUnitUtils.ts
> +  refreshUnitsFromJore?: boolean
This isn't, but the `getProcurementUnitsByInspection` function above is called with false!

I really dislike using "should", it sounds like a test assertion. I almost used it here, but it feels like nails on a chalkboard for me. is/has/ etc is fine.

2021-06-11 03:27 UTC, danieldunderfelt commented on src/inspection/CommonInspectionResolver.ts
> +    draftInspection.minStartDate = getDateString(max([seasonStart, currentProdStart]))
Probably some test change that was mistakenly left in. We did talk about this on Slack...

2021-06-11 08:13 UTC, Divinare commented on src/inspection/validateInspection.ts
> +      end: getDateObject(contract.endDate),
Added a comment about this that the method currently only supports preInspections just to highlight that it can't be used for postInspections

Maybe we should have separate files for pre and post inspections to make more clear which method is common, which one is for only pre/postInspectons

2021-06-11 10:19 UTC, Divinare commented
Tested that inspections now lock contracts and contract procurementUnits properly!

2021-06-11 10:20 UTC, Divinare approved these changes

2021-06-11 10:36 UTC, merged