Inspection date range entity & resolvers
HSLdevcom/bultti pull request #94
Opened 2020-12-02 12:40 UTC by Divinare

2020-12-03 06:29 UTC, danieldunderfelt requested changes

2020-12-03 06:29 UTC, danieldunderfelt commented on src/inspection/InspectionDateEntity.ts
> +  endDate: string
Is there a reason for these to be nullable? I don't think we ever want to fetch or write any InspectionDates which are null to or from the database.

If there is a reason for them to be nullable, also remember to make the class property itself optional with ?.

2020-12-03 06:29 UTC, danieldunderfelt commented on src/inspection/InspectionDateResolver.ts
> +  endDate: string
Class properties of nullable fields should be optional.

2020-12-03 06:29 UTC, danieldunderfelt commented on src/inspection/InspectionDateResolver.ts
> +  }
It could be useful to filter the result by season so that each option in the list is relevant to the inspection. InspectionDate entities could also be related to Season entities, but this is not required.

2020-12-03 06:29 UTC, danieldunderfelt commented on src/inspection/InspectionDateResolver.ts
> +      inspectionDateRepo.create({ startDate, endDate })
It would probably be good to check if the dates already exist before saving a new entity. Otherwise, a user could create limitless InspectionDates with the same dates. Ideally, there would only be one InspectionDate row per date range without overlap.

2020-12-03 08:07 UTC, Divinare commented on src/inspection/InspectionDateResolver.ts
> +  endDate: string
Wanted them not to be nullable. Seems like they are not by default so I removed `{ nullable: false }`

2020-12-03 08:15 UTC, Divinare commented on src/inspection/InspectionDateResolver.ts
> +  }
When we generate options in InspectionForms, some filtering rules need to be implemented. I don't know if we want to filter by season yet, maybe you might want to see options for different seasons, not just the one you have currently selected.

Anyways, I think this should be implemented here when we actually need option filtering: https://github.com/HSLdevcom/bultti/issues/95

2020-12-03 08:18 UTC, Divinare commented on src/inspection/InspectionDateResolver.ts
> +      inspectionDateRepo.create({ startDate, endDate })
Overlap prevention/validation is needed in here yes

2020-12-03 08:48 UTC, Divinare commented on src/inspection/InspectionDateResolver.ts
> +      inspectionDateRepo.create({ startDate, endDate })
Implemented it here. This error should not happen, frontend should prevent user from selecting invalid date. But of course, BE needs to validate it

2020-12-03 09:09 UTC, Divinare commented
Review fixes done ^

2020-12-08 11:35 UTC, danieldunderfelt approved these changes

2020-12-08 11:37 UTC, merged